Creating Postgres dialogue
IDEMSInternational/R-Instat pull request #7898
Opened 2022-09-30 08:37 UTC by derekagorhom

fixes #7828 

This is ready for review
 @lilyclements , Please test using some real-time data / a valid key

2022-10-03 06:57 UTC, N-thony requested changes
Great, just few comments

2022-10-03 06:57 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +        TestOKEnabled()
There is no need to call this sub here since the controlcontentschanged of this control is handled on line 109 where TestOkEnalbed will run

2022-10-03 06:57 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +
one line space,

2022-10-03 06:57 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +
remove the spaces lines 39 and 40?

2022-10-03 06:57 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +        clsGetFormsFunction.SetRCommand("get_postgres_data")
move this after line 65 to simplify the readability

2022-10-03 06:57 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +        End If
this could be simplify by cmdGetData.Enabled = ucrInputUsername.IsEmpty() ???

2022-10-03 06:57 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +    Private Sub ucrInputUsername_ContentsChanged(ucrChangedControl As ucrCore) Handles ucrInputUsername.ControlContentsChanged
on line 109 you are also handling ucrInputUsername.ControlContentsChanged, is this correct?
no need to called TestOkEnalbed here since ucrInputUsername.ControlContentsChanged is handled on line 109

2022-10-03 09:16 UTC, derekagorhom commented on instat/dlgImportFromPostgres.vb
> +        End If
I think we can leave this as it is

2022-10-03 09:19 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +        End If
you can simplify it

2022-10-03 09:46 UTC, derekagorhom commented on instat/dlgImportFromPostgres.vb
> +        End If
done

2022-10-04 11:21 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +    Private Sub ucrInputUsername_ContentsChanged(ucrChangedControl As ucrCore) Handles ucrInputUsername.ControlContentsChanged
Handles ucrInputUsername.ControlValueChanged?

2022-10-04 11:22 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +        clsGetFormsFunction.SetPackageName("postgresr")
move this after line 64

2022-10-04 11:26 UTC, N-thony requested changes
just minor comments

2022-10-07 06:54 UTC, derekagorhom commented
@N-thony i have made the changes

2022-10-07 11:08 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +        ucrBase.clsRsyntax.SetBaseRFunction(clsDefaultRFunction)
You are setting the R command before setting the package,
we normally start by setting the Package before the R command.
So, switch the two lines 64 and 65.

2022-10-07 11:13 UTC, N-thony commented on instat/dlgImportFromPostgres.vb
> +
one line space

2022-10-07 11:14 UTC, N-thony requested changes
just some useful comments

2022-10-10 12:26 UTC, derekagorhom commented
@N-thony can check the changes again

2022-10-22 20:20 UTC, lilyclements reviewed
Thank you for being patient while waiting for this review! It's looking good - I am happy to give you the key/code to be able to test this yourself.

1. The text at the top of the dialog is currently "dlgImportFromPostgres" - can you change this text to something more user friendly, like "Import from Postgres" (or a suitable name)
2. Can you sort the tab order? If you don't know how to do this, it is under "View > Tab Order" on the designer page. Do you know what this does?

2022-10-22 20:20 UTC, lilyclements commented on instat/dlgImportFromPostgres.vb
> +        clsGetFormsFunction.SetRCommand("get_postgres_data")
If you click "Get Forms" we want a new dialog to pop up that takes the password.
Once the password is given and the user presses OK, the code run should be:
```
plh_con <- DBI::dbConnect(RPostgres::Postgres(),
user = "USER_VALUE",
dbname = "DB NAME VALUE",
host = "HOST VALUE",
port = "PORT VALUE",
password = "PASSWORD")
```
This code runs once the user has clicked "OK" on the "Get Forms" password box.

Once OK is clicked, the input box is filled with the contents that come when the following is run:
`DBI::dbListTables(plh_con)`
 A similar thing occurs in the ImportFromODK dialog.
The user can then select their form.

Then want the base function to be `get_postgres_data` in the `postgresr` package.
This runs
```
postgresr::get_postgres_data(site = plh_con, name = "VALUE IN INPUT")
```

2022-11-03 06:14 UTC, N-thony commented
@derekagorhom is this ready for re-review?

2022-11-03 07:23 UTC, derekagorhom commented
> @derekagorhom is this ready for re-review?

not yet

2022-11-14 07:33 UTC, N-thony commented
> > @derekagorhom is this ready for re-review?
> 
> not yet

@derekagorhom any uppdate?

2023-01-04 10:24 UTC, lilyclements commented
@derekagorhom I suggest a suitable next step is for us to have a meeting with @Patowhiz to discuss how this dialog can fit into our other dialog(s) that import from SQL. @Patowhiz what do you think?

2023-01-04 10:49 UTC, derekagorhom commented
Yes please, I agree

2023-01-05 10:20 UTC, Patowhiz commented
@lilyclements @derekagorhom. Sounds good. Happy for any one of you to schedule the meeting

2023-01-07 10:31 UTC, derekagorhom commented
@lilyclements , @Patowhiz would thursday Jan 12 be ok for us to have a meeting? 
thanks

2023-01-09 10:38 UTC, lilyclements commented
@derekagorhom I can do Thursday before 1300 GMT. Does that suit?

2023-01-11 08:03 UTC, derekagorhom commented
> @derekagorhom I can do Thursday before 1300 GMT. Does that suit?

Yes please, I will send the zoom link

2023-01-12 07:11 UTC, derekagorhom commented
Derrick Agorhom is inviting you to a scheduled Zoom meeting.

Topic: Sql Import Dialogue meeting
Time: Jan 12, 2023 12:00 PM London

Join Zoom Meeting
https://us04web.zoom.us/j/71169683961?pwd=eJWAeygRF4aQbI1cRNXbunVVr6Yerd.1

Meeting ID: 711 6968 3961
Passcode: eA1Wds

@lilyclements , @Patowhiz here is the link

2023-01-12 12:03 UTC, Patowhiz commented
@derekagorhom I've joined the meeting but no one is there.

2023-01-12 12:28 UTC, derekagorhom commented
> @derekagorhom I've joined the meeting but no one is there.

sorry the meeting is supposed to start at 1:00 GMT, 
i have made a new link 

Derrick Agorhom is inviting you to a scheduled Zoom meeting.

Topic: Sql Import Dialogue meeting
Time: Jan 12, 2023 01:00 PM London

Join Zoom Meeting
https://us04web.zoom.us/j/71169683961?pwd=eJWAeygRF4aQbI1cRNXbunVVr6Yerd.1

Meeting ID: 711 6968 3961
Passcode: eA1Wds

2023-02-07 09:41 UTC, derekagorhom commented
@lilyclements and @Patowhiz  as per our last meeting i changed this dialogue to the general SQL dialogue. 
can you have a look at it. 
thanks

2023-03-09 15:14 UTC, lilyclements commented
@Patowhiz @derekagorhom how is this getting on? :)

2024-06-15 09:42 UTC, rdstern commented
@lilyclements this sounds a useful addition.  Would you still like it to proceed?

2024-06-17 11:27 UTC, lilyclements commented
@rdstern yes, this would be a great addition for R-Instat. However, @Patowhiz pointed out that there are some parallels between this and our import from Climsoft dialog since we are using Postgres for both.
@Patowhiz @rdstern do we want this as a separate dialog, or a more general dialog on importing from postgres databases? 

How things are now with the ParentApp side of things, this would be more "Import from Open App Builder", for when that is built. Open App Builder is going to be a "product" so perhaps having this as it's own dialog would be great. @ChrisMarsh82 might be able to add some input in here on this.

I suggest we close this for now, I will amend the issue (or close the issue and start a new one), and we can instead have "Import from Open App Builder" when our OAB system is set up?

2024-09-19 06:57 UTC, rdstern commented
@Patowhiz has now made quite a few changes to his importing from climsoft dialog and they have now just been merged.
So its clear they are separate dialogs.
@lilyclements are you still planning to close this one?

2024-09-19 15:20 UTC, lilyclements commented
@rdstern thanks, I will close this. @Vitalis95 completed this (very nicely too!) in PR #9121

2024-09-19 15:20 UTC, closed without merging