Added Label Outlier Check Box and Minor Design changes on Boxplot Dialog.
IDEMSInternational/R-Instat pull request #8271
Opened 2023-04-18 14:47 UTC by MeSophie

Fixes partially #8242.
@rdstern I fixes part a) and b).

@lloyddewit @WezzieBanda please can you have a look?

2023-04-23 06:00 UTC, rdstern requested changes
@MeSophie good to get started.  
a) But sorry I misled you - it is not the `Plot Options` to move to the right, instead it is the `Horizontal Plot` option.

b) And I notice you already added the Geom_text option into that pull-down.  That's great, but could you just call it Text Options.

c) And move the Tufte Option up one control.  Later I am sure you will have more controls to add to the new row with the Label options.

And hopefully get help from Wezzie on the code and options to use for the labels

2023-04-24 14:25 UTC, WezzieBanda commented
@MeSophie The dialogue seems not to be working for me, I believe it has to do with how the sta_summary_fun was incorporated in the code.
![Boxplot label](https://user-images.githubusercontent.com/106272881/234026300-cf914413-3729-4258-9922-97d9e4bfa40f.PNG)

2023-04-24 17:13 UTC, WezzieBanda commented
@MeSophie looks good.

2023-04-25 14:45 UTC, lloyddewit requested changes
@MeSophie Looks good to me, just one small question

2023-04-25 14:45 UTC, lloyddewit commented on instat/dlgBoxPlot.vb
> +    Private Sub ucrPnlPlots_ControlValueChanged(ucrChangedControl As ucrCore) Handles ucrPnlPlots.ControlValueChanged, ucrChkTufte.ControlContentsChanged, ucrChkAddPoints.ControlValueChanged
this sub doesn't seem to do anything, remove it?

2023-05-03 07:49 UTC, rdstern requested changes
@WezzieBanda and @MeSophie this is looking very promising.  It seems to work!  Well done.

But there are a couple of challenges still:

a) When I change the coefficient from 1.5 the boxplot changes, but the labelled outliers are still for the default value of 1.5.  Can the code for the outliers reflect the coefficient used?

![image](https://user-images.githubusercontent.com/11226469/235856693-31fdf57c-da5a-4f56-ae33-bfd0b3fa2538.png)



b) I also tried an example where there are no outliers and it then gives an error.  An example is our usual survey data with yield against Variety.  (It works fine with yield against Village, where there is just one outlier.)
c) And a - i hope trivial design change.  Could you swap the Add Points and the Label outliers on the Left of the dialogue.  Then you could move the Tufte option up one place on the right.  (It looks lonely down there now!)  And could you change Tufte Boxplots to Tufte Boxplot (so singular), to be consistent with the option at the top. 
d) And another one.  The label outliers is only for the Boxplot option.  It does not apply to the jitter or the violin plots.

2023-05-03 10:03 UTC, N-thony commented on instat/static/InstatObject/R/stand_alone_functions.R
> +  o <- boxplot.stats(y)$out; if(length(o) == 0) NA else o
can you rename this variable correctly, something like
out <- boxplot.stats(y)$out; if(length(out) == 0) NA else out

2023-05-05 14:47 UTC, MeSophie commented
@rdstern I'm done with the parts a), c) and d). I added one control  for `Size` for part a) for now is the only way that I see to play with the size of outlier label. I'm still investigate of part b).

2023-05-06 08:52 UTC, rdstern commented
@MeSophie this is promising.  I think you can make some further progress, but then, for efficiency you might then wait for some help on the R-code from @lilyclements.  This may not be till the week of 12 June, when she will be visiting Kenya (though you are still likely to be working from home then.).
a) The outliers are still given for the coefficient of 1.5, even when you change the coeff.
b) As mentioned above, there is an error if there are no outliers (saurvey data with yield v variety is an example.
c) I am afraid a new one - the outlier is only the y variable.  The code gives examples where you may wish to label another variable, e.g. the date.  This will change the dialogue a bit to add space.
d) When it is working it would be good to add the same to the Climatic > Check Datat Boxplot dialogue - so consider this as the coding is done, i.e. that you will be using it in 2 dialogues.

On the boxplot design - point c, you may wish to move the Horizontal Plot control back to the Left.  Then you can move Tufte up and add a checkbox with label Variable: (default unchecked.  If checked, then it opens a single receiver that can take a variable to be plotted.

2023-07-06 08:53 UTC, N-thony commented
> @MeSophie this is promising. I think you can make some further progress, but then, for efficiency you might then wait for some help on the R-code from @lilyclements. This may not be till the week of 12 June, when she will be visiting Kenya (though you are still likely to be working from home then.). a) The outliers are still given for the coefficient of 1.5, even when you change the coeff. b) As mentioned above, there is an error if there are no outliers (saurvey data with yield v variety is an example. c) I am afraid a new one - the outlier is only the y variable. The code gives examples where you may wish to label another variable, e.g. the date. This will change the dialogue a bit to add space. d) When it is working it would be good to add the same to the Climatic > Check Datat Boxplot dialogue - so consider this as the coding is done, i.e. that you will be using it in 2 dialogues.
> 
> On the boxplot design - point c, you may wish to move the Horizontal Plot control back to the Left. Then you can move Tufte up and add a checkbox with label Variable: (default unchecked. If checked, then it opens a single receiver that can take a variable to be plotted.

@MeSophie any progress? Also, this PR has conflicts, can resolve them?

2024-01-09 09:31 UTC, rdstern reviewed
@MeSophie this is not urgent compared to your other work.  But it would be nice if easy, given you have started.
a) When I change the coefficient for the boxplot, this is ignored and I still get the default labels from coeff 1.5.
b) I get an error if there are no outleirs.  For example survey yield against variety.  Against village it works fine, as there is one outlier.

2024-01-09 09:52 UTC, MeSophie commented
> @MeSophie this is not urgent compared to your other work. But it would be nice if easy, given you have started. a) When I change the coefficient for the boxplot, this is ignored and I still get the default labels from coeff 1.5. b) I get an error if there are no outleirs. For example survey yield against variety. Against village it works fine, as there is one outlier.

@rdstern I'm on it for part b) if we remove the `outlier.colour="red"` parameter as a defaut value of boxplot function ( `(ggplot2::geom_boxplot(outlier.colour="red"))`) so that the user can take this parameter from sub dialog it will solve the bug.
For part a) i'm still investigating on it if @lilyclements can help here it will be great.

2024-01-10 07:33 UTC, MeSophie commented
@rdstern I have fixed part b). For part a) I definitively need some help from @lilyclements because in R I have tried to edit the coef  in referents codes giving on [adding label](https://stackoverflow.com/questions/33524669/labeling-outliers-of-boxplots-in-r). But I still having the same problem.

2025-06-09 20:25 UTC, MeSophie commented
This is replace by PR #9804

2025-06-09 20:25 UTC, closed without merging