Bug fixes in General Summary Dialogue
IDEMSInternational/R-Instat pull request #8821
Opened 2024-02-19 08:30 UTC by N-thony

Fixes #8744
@rdstern I don't get the script you have posted in the issue but I fixed some bugs reported there. Have a look

2024-02-20 14:48 UTC, rdstern commented
@N-thony there is one other obvious problem to fix - if you can, before I discuss with David?

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/f4afd75f-64c5-43bc-afe7-db584b204066)

If I load the diamonds, go into the dialog and press Add I get this, and without the dataset.  I assume it should access the diamonds data in the control, as the data selector usually does.  I wonder why not?

2024-02-21 17:15 UTC, rdstern reviewed
@N-thony excellent.  I still don't know how to use it, or if the results are correct.  I'll discuss with @volloholic and then comment further.

2024-02-23 17:34 UTC, rdstern commented
@N-thony thanks for the improvements so far.  I have been through a calculation with David, and can now get it to work, for something simple, by making the corrections in the script window.  The current problems may have been there all along, or perhaps your corrections may have had an unfortunate side effect.  I take you through this calculation step-by-step in case you can see obvious bugs in the front-end, once you see the errors in the generated code.

a) So diamonds data - always start on that data frame
b) Dialog > Add > Manipulations > as shown below:  (any number of the factors.  I have tried with just one, this is my first time with all 3.)

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/1cd4f7c0-f85c-4abd-bc61-02d9762a5877)

c) Return and back to Main and Type = Summary:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/55e7896b-0deb-4d62-bdbd-571ce6a3e18c)

d) Get the mean of price in the calculator - call the result antoine as shown:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/d860962a-1fd8-417c-8858-01aa6d19d580)

e) Return and To Script:

Here is the script I get:

```
# Dialog: General Summaries

calc1 <- instat_calculation$new(name="calc1", type="summary", save=2, result_name="antoine", manipulations=list(manip1=instat_calculation$new(name="manip1", type="by", save=0, result_name="", calculated_from=list(diamonds = "color",diamonds = "clarity",diamonds = "cut",))), function_exp="mean(price , na.rm = TRUE)", calculated_from=)
data_book$run_instat_calculation(calc=calc1, display=FALSE)
rm(calc1)
```
There are 2 problems to be corrected in the script:
a) There is an extra comma at the end here:  `calculated_from=list(diamonds = "color",diamonds = "clarity",diamonds = "cut",`
b) This is blank  `calculated_from=` at the end of the command.  It should (I think) be: `calculated_from=list(diamonds = "color",diamonds = "clarity",diamonds = "cut",diamonds = "price")`  
(I notice that just  `calculated_from=list(diamonds = "price")`  will also run, but David thinks that the general system may sometimes need the full list.)

Then I get the result:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/ebf74873-e270-4ee6-b708-080a2a354f27)

We are hoping that you can see some obvious places in the code where these bugs arise?  Good luck!  I am also happy to take you through these steps on my screen if that would help.  I would very much like to get this powerful system working so it can also be documented.  It is quite a challenge without Danny.

2024-02-26 09:37 UTC, rdstern reviewed
@N-thony that's brilliant and a great relief.  I am discussing again with @volloholic this afternoon and will report in more detail then.
But so good that it is starting to work again.

One "small?" thing you may be able to improve quickly is as follows.  Here is the code for something that works fine now:

```
# Dialog: General Summaries
calc1 <- instat_calculation$new(name="calc1", type="summary", save=2, result_name="gg", calculated_from=list(diamonds = "carat",diamonds = "cut",diamonds = "color",diamonds = "clarity",diamonds = "depth",diamonds = "table",diamonds = "price",diamonds = "x",diamonds = "y",diamonds = "z",diamonds = "james"), manipulations=list(manip1=instat_calculation$new(name="manip1", type="by", save=0, result_name="", calculated_from=list(diamonds_by_cut_color_clarity = "cut",diamonds_by_cut_color_clarity = "color",diamonds_by_cut_color_clarity = "clarity"))), function_exp="min(depth , na.rm = TRUE)")
data_book$run_instat_calculation(calc=calc1, display=FALSE)
```
But I notice the first `calculated from` includes all the variables in the dataframe.  So I tried again with the efc data from sjplot package that has 26 variables and it is here:

```
# Dialog: General Summaries
calc1 <- instat_calculation$new(name="calc1", type="summary", save=2, result_name="roger", calculated_from=list(efc = "c12hour",efc = "e15relat",efc = "e16sex",efc = "e17age",efc = "e42dep",efc = "c82cop1",efc = "c83cop2",efc = "c84cop3",efc = "c85cop4",efc = "c86cop5",efc = "c87cop6",efc = "c88cop7",efc = "c89cop8",efc = "c90cop9",efc = "c160age",efc = "c161sex",efc = "c172code",efc = "c175empl",efc = "barthtot",efc = "neg_c_7",efc = "pos_v_4",efc = "quol_5",efc = "resttotn",efc = "tot_sc_e",efc = "n4pstu",efc = "nur_pst"), manipulations=list(manip1=instat_calculation$new(name="manip1", type="by", save=0, result_name="", calculated_from=list(efc = "e15relat",efc = "e16sex"))), function_exp="mean(e17age , na.rm = TRUE)")
data_book$run_instat_calculation(calc=calc1, display=FALSE)
```
 
So clearly it will be unmanageable for any wide dataset.  Could you change this first?

2024-02-29 07:19 UTC, rdstern commented
@N-thony yes, just make the list of variables include those that are needed in that operation?  Remember the data frame may have even 1000's of variables!

2024-02-29 09:50 UTC, rdstern submitted a review, later dismissed
@N-thony great, that looks neat and still gets the answers for the simple example I am using.  @Patowhiz could you do a quick check and then merge?  The current code and dialog don't work at all, so this has to be better!

2024-02-29 11:35 UTC, Patowhiz requested changes
@N-thony looks good just a few comments and suggestions.

2024-02-29 11:35 UTC, Patowhiz commented on instat/sdgCalculationsSummmary.vb
> +        'ucrCalcSummary.ucrReceiverForCalculation.bAttachedToPrimaryDataFrame = False
Remove this entirely if comment is not for future reference?

2024-02-29 11:35 UTC, Patowhiz commented on instat/sdgCalculationsSummmary.vb
> +            Dim strDataName = lstVariables(i)
Explicitly define the variable type for self documenting code.

2024-02-29 12:10 UTC, rdstern approved these changes
@Patowhiz still seems ok to me, so approving again

2024-02-29 12:19 UTC, merged