Displaying multiple tables (html) in the output window
IDEMSInternational/R-Instat pull request #8887
Opened 2024-03-20 06:50 UTC by N-thony

Fixes #8855
@rdstern I couldn't reproduce your example in the corresponding issue on having multiple tables to the default browser. 
This is a quick check but will still investigate on having the multiple tables in output window rather than default browser. Can you test this?

2024-03-21 03:31 UTC, rdstern commented
@N-thony that would be really great, but I don't have any current dialog to test this with?  The obvious one is the Describe > 2/3 Variable summarise.  Maybe you could tweak the code for this dialog in this pull request?

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/c00ff97c-305a-4177-9de5-8b82db0065e5)

Currently it just gives the table for village.  It ignores the 2nd factor in the multiple receiver.

2024-03-24 01:00 UTC, rdstern submitted a review, later dismissed
@N-thony that's great.  I like it a lot.  @Patowhiz can you check and merge if ok?

2024-03-24 11:21 UTC, Patowhiz reviewed
@N-thony kindly add comments to code changes in` clsRLink.vb` and `instat_object.R`. This will help me understand the changes better and will be useful in future maintenance.

2024-03-24 11:25 UTC, Patowhiz reviewed
Also try using RStudio formatting options when editing the R files. It help with having consistency in the line formats in those files.

2024-03-24 11:34 UTC, Patowhiz commented on instat/static/InstatObject/R/instat_object_R6.R
> +  } else {
I recommend you implement these changes inside `view_object_data` function  instead of `get_object_data` function. They relate more to viewing the object data as file than getting the object data. I also think it will be more efficient and clear when done inside `view_object_data`.

2024-03-25 09:23 UTC, Patowhiz commented on instat/clsRLink.vb
> +            Dim arrFilesPaths() As String = strOutput.Split({vbCrLf, Environment.NewLine}, StringSplitOptions.RemoveEmptyEntries)
Considering that strOutput always uses `Environment.NewLine`, you don't have to use `vbCrLf` when splitting it to array. Using `Environment.NewLine` is enough.

2024-03-25 09:26 UTC, Patowhiz commented on instat/clsRLink.vb
> +                    Path.GetExtension(_path).Equals(".html", StringComparison.OrdinalIgnoreCase)) Then
The file exist check is done by `GetFileOutput` function. You can simply use `bAsFile` to check whether you should iterate the strOutput or not.

2024-03-25 09:27 UTC, Patowhiz commented on instat/clsRLink.vb
> +            strFilesPath = If(arrFilesPath.Length = 0, "", String.Join(Environment.NewLine, arrFilesPath))
You don't need to recreate the `strFilesPath` from the array, The array was derived by `arrFilesPath`.

2024-03-25 09:33 UTC, Patowhiz commented on instat/static/InstatObject/R/stand_alone_functions.R
> +    file_name <- tempfile(pattern = paste0("viewhtml_", i, "_"), fileext = ".html")
Calling `file_name <- tempfile(pattern = "viewhtml", fileext = ".html")` will guarantee unique name, so the concatenation of the index `i` is not really necessary. I recommend removing it for simplicity.

2024-03-25 16:50 UTC, Patowhiz requested changes
@N-thony I have made a few comments and request for changes. Thanks.

2024-03-25 16:50 UTC, Patowhiz commented on instat/static/InstatObject/R/stand_alone_functions.R
> +      file_names[[i]] <- view_html_object(html_object[[i]])
I noticed that in scenarios where `html_object[[i]]` is a list ,  `file_names[[i]]` will also end up having a list, which might cause unexpected behavior for functions dependent on this one.

I understand that you are trying to use recursions to achieve what could be done with a simple `for` loop. While recursion can be elegant, in this case, a `for` loop would be more optimal and clearer. For instance, in scenarios where `html_object` is a list, the check `if (is.list(html_object) && all(sapply(html_object, class) == class(html_object[[1]])))` is executed for each element in `html_object`. This redundancy makes the recursion inefficient.

Additionally, it took me a while to reproduce the possible bug that I just outlined above, which further supports the need for a more straightforward approach.

I recommend refactoring the recursive logic into a `for` loop to enhance both performance and code readability.

2024-03-25 20:31 UTC, Patowhiz requested changes
@N-thony, this is quite insightful. We will definitely want to extend this functionality to handle other formats like text and graphs in the future, but that can be addressed later.

I noticed that some valuable comments have been removed from the `view_html_object` function in R. Please re-insert these comments into their appropriate code blocks. These comments were added to explain the rationale behind certain decisions related to various outputs. In the future, I plan to introduce generic solutions based on these decisions. Removing these comments could hinder future developers or myself from quickly grasping the reasons behind these decisions. It's worth noting that the comments include the dates when these decisions were made, highlighting the importance of retaining these comments within the function.

2024-03-26 07:15 UTC, Patowhiz approved these changes

2024-03-26 07:20 UTC, Patowhiz commented
@rdstern, kindly retest this before giving your approval. Additionally, please test other dialogs that produce various types of output objects to ensure that we haven't inadvertently introduced any regressions. Apologies for the inconvenience, but you are our "unit tests" for these scenarios.

2024-03-26 17:32 UTC, rdstern commented
I tried the same as shown in the dialog above.  It works fine in the dialog.

I then did To Script and tried the script, which was as follows:

```
# Dialog: Describe Two Variables

survey <- data_book$get_data_frame(data_name="survey")
last_table <- survey %>% purrr::map(.x=c("village","variety"), .f=~data_book$summary_table(data_name="survey", treat_columns_as_factor=FALSE, summaries=count_label, factors=c("fertgrp",.x), columns_to_summarise=.x) %>% pivot_wider(names_from={{ .x }}, values_from=value) %>% gt::gt())
data_book$add_object(data_name="survey", object_name="last_table", object_type_label="table", object_format="html", object=last_table)
data_book$get_object_data(data_name="survey", object_name="last_table", as_file=TRUE)
rm(list=c("last_table", "survey"))

```
This gives an error, see below.  When running line-by-line the error is in the `data_book$get_object_data function`.

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/566753de-0240-4c00-b49a-08f15e5ec315)

2024-03-26 22:35 UTC, rdstern approved these changes
@N-thony this is great.  I am approving.  I tried just a few more dialogs.
My only query is the code generated.  I made variety into a factor, so I had 3 tables generated.  
The code, when I ran from the script looks fine and now runs well.  It seems a lot neater even than the code when run from the dialog, because it just repeats the last main line,before each table.  When running from the dialog it repeats the whole code before each of the 3 tables?

2024-03-27 08:45 UTC, Patowhiz commented
@rdstern did you test other dialogs that produce various types of output objects to ensure that we haven't inadvertently introduced any regressions?

2024-03-27 10:03 UTC, rdstern commented
@Patowhiz I have tried some - including the calculator, and various from the describe menu that produce graphs and tables.  So far, so good.  I also wonder about these dialogs where we disabled the Both option, when you redid the output window?

Perhaps they could now be re-instated?  It is not high on my list of priorities, but might be a good additional test to see if they now work easily:

This is 2-way - there is also 3-way:

<img width="323" alt="image" src="https://github.com/IDEMSInternational/R-Instat/assets/11226469/53f946ae-fb06-42bf-9f0f-48d73353ff8c">

2024-03-28 09:30 UTC, Patowhiz commented
@rdstern sounds like a good task for @N-thony and @Vitalis95 to look into those dialogs once they become a priority.

2024-03-28 09:32 UTC, Patowhiz approved these changes

2024-03-28 09:33 UTC, merged