Added Recovery Option dialogue in the Tools Menu
IDEMSInternational/R-Instat pull request #8970
Opened 2024-05-06 15:09 UTC by derekagorhom

Fixes #3885 
Replace #8825

@rdstern we have made the changes for items b and c for [this comment](https://github.com/IDEMSInternational/R-Instat/pull/8825#issuecomment-2095969201)

This is ready for review

2024-05-06 16:50 UTC, rdstern approved these changes
@derekagorhom and @N-thony this now seems to be working completely!  Wonderful if really true.  I have now reset the backing up interval back to 10 minutes.  (I was asked to set it to 1 minute for the testing.)
@lloyddewit are you happy to review this one as it relates to the script/log window?  Otherwise I'll ask Patrick to review.
What I think is working now is as follows:
a) Backing up is notified to the current log file.  This was separate, by Antoine.  It looks nice and includes the date/time.
b) The backup is, as before to the data book and the log file.
c) These are both available (from the previous session) when you restart R-Instat.  That's whether you crashed or not.  This is in the Tools > Restore dialog.
d) Once the current session is backed up, the backup from the previous session is no-longer available.  
e) Also the log file options from the current session are now disabled, because they are also, possibly more up-to-date, in the log tab of the script window.
f) However, the backed-up data book is available.  If chosen it will replace the current data book.  
g) Then - not tested, but exciting - we could run the log file on from there as much as we want.  So, if we have just messed up our data, and users have the skills to do this, then we now have the ultimate undo in R-Instat!

2024-05-07 07:15 UTC, lloyddewit commented
@rdstern @derekagorhom Happy to see this. If it works as @rdstern says then it's a powerful feature that could potentially be extended to allow rollback to any point in the log file. I had a look at the code and I couldn't see anything that's incompatible with the script window. I think it's best if @Patowhiz or another developer does the official peer review and approval.

2024-05-08 10:31 UTC, Patowhiz requested changes

2024-05-09 08:43 UTC, derekagorhom commented on instat/dlgRestoreBackup.vb
> +        End If
@Patowhiz  i tried doing the change and now i get no results from the data option and the log option

2024-05-10 07:58 UTC, Patowhiz commented on instat/dlgRestoreBackup.vb
> +        End If
@derekagorhom if you are getting no results it means there is something wrong with your code. You could ask @N-thony for assistance.

2024-05-13 09:30 UTC, derekagorhom commented on instat/dlgRestoreBackup.vb
> +        End If
@Patowhiz i have made the change

2024-05-13 14:06 UTC, rdstern commented
@derekagorhom I got build errors, so couldn't proceed.

2024-05-13 15:22 UTC, rdstern approved these changes
@derekagorhom this still seems ok to me.  As a minor point I note the bottom left message changes from the name of the current data frame to no data loaded.  If you move data frames, then it gives the name of the new one, until the next backup, when it goes back to no data loaded.  
That's a confusing message.  @N-thony could it say backup at 15:43.  It just gives the time, to the minute, as the date isn't needed.  (That's correctly given with the date by Antoine in the log file.)  If not included this time, can an issue be made.
Please @Patowhiz could we get this feature merged before Thursday?  Then I can report to Stephen.

2024-05-15 08:49 UTC, derekagorhom commented on instat/frmMain.vb
> +            clsRLink.AppendToAutoSaveLog(strBackupMessage)
@Patowhiz this a feature @rdstern personally requested to enable the user know the time with which a data file was backed up.
If you want further clarification i think you can ask roger directly

2024-05-15 09:09 UTC, Patowhiz commented on instat/frmMain.vb
> +            clsRLink.AppendToAutoSaveLog(strBackupMessage)
@rdstern for clarity, do you want this logged here so that users can be able to determine up to what point they would like to execute the logged scripts?
I'm trying to understand the significance of this feature then we can discuss how it can be included in a coherent way. At some point, we want to merge certain scripts functionalities of the script window with the output window. So I think separating 'debug scripts' and 'user scripts' is crucial.

2024-05-15 09:36 UTC, rdstern commented
@Patowhiz I hope we are talking about the same point.  Here is currently the data window after backing up:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/c766107a-4d92-4ab8-af0e-511e9b97260b)

Notice at the bottom left it says "No data Loaded".  That's because the backup was run.  That statement is not helpful and is also untrue.  So I was merely requesting it be changed.  I hope you agree?

Now I can chnge it, by changing the data frame, see below:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/fa2322ee-fb5d-41c1-aa8c-759e39818e5d)

But it doesn't change if I have only a single data frame loaded.  

Now I am ok with the name being the current data frame, but I don't like it saying No Data Loaded.  Then I wondered if it could say something more useful.  It sort of freezes (with a large dataset) when it is backing up, so I wondered if it then says that it backed up, and when (just hours and minutes) could be useful to the user.  Hence my suggestion.

That links with the "ultimate undo" that we now have via this dialog.  If you mess up, then you can now re-load the last backup data at any time.

2024-05-15 09:55 UTC, rdstern commented
@derekagorhom and @Patowhiz  oh that point d).  Tha\'s already done and merged I think.  That's the message in the log file and was done by @N-thony .  I was very happy with that.

I thought @Patowhiz was querying the message at the bottom of the data window.  I have replied on that point above.  Nice if something can be done - as the current situation looks unprofessional.  But not that important.  I am keen on progress and if that means skimping on some details then so be it.

2024-05-15 10:00 UTC, derekagorhom commented on instat/frmMain.vb
> +        End Try
@Patowhiz i have made the changes, can you review it again

2024-05-15 10:01 UTC, derekagorhom commented on instat/frmMain.vb
> +        If strAutoSavedLogFilePaths.Length > 1 Then
done

2024-05-15 10:01 UTC, derekagorhom commented on instat/dlgRestoreBackup.vb
> +    Private strAutoSaveInternalLogFolderPath As String = Path.Combine(Path.GetTempPath, "R-Instat_debug_log_auto_save")
done

2024-05-15 12:30 UTC, Patowhiz commented
> a) @derekagorhom those are all good changes. I note that the saving seems to take place when the option is chosen. In the file menu the saving needs an extra button. I am sort of assuming that here it will take place when Ok is pressed. b) I note that the Close is now cleaner. c) I am not sure how much more Derek will do, on this dialog, before @N-thony takes over? d) Could you also include the task here of adding to the log file, when backing up is done? I am thinking of perhaps 3 comment lines each time. Perhaps:
> 
> ```
> ##########
> ## Backing up data and log files  on: *Maybe add current date and time here*
> ##########
> ```

@rdstern I was querying about something related to the comment you mention in issue #8825 as pointed by @derekagorhom above. The question below relates to the quoted comment above.

@rdstern for clarity, do you want this logged here so that users can be able to determine up to what point they would like to execute the logged scripts?
I'm trying to understand the significance of this feature then we can discuss how it can be included in a coherent way. At some point, we want to merge certain scripts functionalities of the script window with the output window. So I think separating 'debug scripts' and 'user scripts' is crucial.

2024-05-15 13:00 UTC, Patowhiz commented
@rdstern @derekagorhom, I hope you have tested the performance, especially when there are many data frames open and R-Instat has been running for an extended period with numerous operations. I'm concerned that the backup operations, which involve creating copies of files, might be time-consuming in such scenarios.

@derekagorhom given the .NET version we are currently using, in future I recommend performing disk I/O operations like this in a separate thread instead of the main thread. 

@rdstern I can still merge this as it is then you can continuously test it before we make a stable release.

2024-05-15 13:35 UTC, rdstern reviewed
@derekagorhom and @Patowhiz in answer to Patrick's queries I am really keen to get this merged.  However on my first try it looks like this:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/28db543e-883b-46ba-9644-ca9e6d1f8e06)

I was hoping that would never happen, i.e. you could always now start by the last version that was backed up.  I suppose there are scenarios where that ias not the case; possibly when the last time I used it, it just wasn't backed up.  Maybe that is what I did?  I am going to check more.

Patrick also asks 2 very good questions, and they might imply @N-thony needs to work on this feature more.

a) With the old version I have had instances when the backing up took an inconveniently long time (during which R-Instat appears to be frozen).  The main time was during the climatic workshop at CIMH.  So I would like to know if efficiencies can be made.
b) Patrick mentions using another thread for the backing up.  Might this mean we could continue with (some) other work at the same time?  That would be great, if possible?

Still testing and I'll comment further soon.

2024-05-15 13:53 UTC, rdstern submitted a review, later dismissed
@Patowhiz I have tried again and it allowed to recover the data used last time.  So I am approving.  If you are happy to merge, then I agree we should continue the testing with the merged version.  It is an exciting improvement and I am keen to add it to the documentation.  That will be a good time for me to continue testing.  And I would like to Derek and Antoine also to reflecr, before a released version - especially on the 2 points you raised.

2024-05-15 15:41 UTC, Patowhiz requested changes
@derekagorhom just a few comments and minor requests and I'll merge. Thanks.

2024-05-15 15:41 UTC, Patowhiz commented on instat/frmMain.vb
> +                    Dim sortedFiles = files.OrderByDescending(Function(f) f.LastWriteTime)
@derekagorhom please add the type of the variable here. It helps with compile time checks.

2024-05-15 15:41 UTC, Patowhiz commented on instat/frmMain.vb
> +                    Dim filesToDelete = sortedFiles.Skip(retentionCount)
Add types here too and anywhere else that you have dynamic variables.

2024-05-15 15:41 UTC, Patowhiz commented on instat/dlgRestoreBackup.vb
> +    Public strAutoSaveInternalLogFolderPath As String = Path.Combine(Path.GetTempPath, "R-Instat_debug_log_auto_save")
@derekagorhom, you could try to eliminate these variables in favor of `frmMain` variables in a separate PR. Reducing duplications whenever possible is important, as it adheres to the Single Responsibility Principle which aims for coherence and robustness of code.

2024-05-16 09:40 UTC, derekagorhom commented
@Patowhiz  i have made the changes. can you review this again
thanks

2024-05-16 10:36 UTC, Patowhiz approved these changes
@derekagorhom thanks.
@rdstern once you review this, I'll merge.

2024-05-16 11:13 UTC, rdstern approved these changes
@Patowhiz and @derekagorhom I am approving so this can be merged.
Patrick suggested that maybe this task could be handled in a different thread.  Is that possible.  I note that almost every task in R-Instat involves sending information to R and this one does not.
I also report that I have had an occasion when I repeatedly cursed the delay in my work, because the backing up was taking long (more than 1 minute - out of 10).  This was with daily climatic data from about 8 stations - so reasonably large, but we have used larger.

I have no idea how much work this would be however, nor who could do it.  For example could it be done by Derek with help and advice from Antoine and/or Patrick?  Or is it a Patrick, only, job?

2024-05-16 11:31 UTC, Patowhiz commented
@rdstern, I'll discuss the implementation with @derekagorhom tomorrow, and then they can attempt to do it.

Anything that relies purely on .NET can be done on a separate thread. However, anything that relies on R can only be done on R's single thread, which means we have to wait for the R task to finish. This is a limitation of R itself. When we send tasks to R, we create a thread and enforce waiting because of R's single-threaded nature.

The waiting you experience is due to our reliance on R to save the data book into a file. This involves disk writes, which can be slow in a single-threaded process. There are ways to mitigate this by leveraging newer in-memory technologies like [DuckDB](https://duckdb.org/docs/api/r.html) to bypass certain limitations. However, this might be overkill if we want to strictly maintain our dependency on R.

2024-05-16 11:31 UTC, merged