Fixed the error caused by attach and detach functions when there is no data in Calculator
IDEMSInternational/R-Instat pull request #8972
Opened 2024-05-08 06:46 UTC by N-thony

Fixes partially #8872 
@rdstern have a look.

2024-05-08 10:24 UTC, rdstern commented
@N-thony it is looking good and I especially like the way it now works cleanly also when there is no data frame.
With a data frame the one bit I still don't like is here:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/d43f7d0b-a054-43a6-a98c-f811975bec03)

With the survey I do a simple calculation calc <- fert * 2, which is fine with Ok.  But when run from the script the data_book$get_columns_from_data puts the result correctly into the grid, but also gives a copy in the output window.  Could there be a small change in that function, so it only outputs to the grid?

2024-05-13 07:17 UTC, rdstern commented
@N-thony great.  What do you suggest?  
a) Should `To Script `therefore not generate those lines, when using the calculator?
b)  or just generate them, but with the comment `(#)` added?  
c) Or is that a job for the user (to add the comment) when running from the script?

I wonder if this is just a `prepare > calculator `script problem or also in other dialogs?

2024-05-13 09:07 UTC, rdstern commented
@N-thony now it seems to work fine from the script window.  

But, when I do fert * 2 from the survey data in the calculator and don't save, so it goes into the output window I now get:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/44b254e5-8bbd-4c9e-9355-a51456310f73)

I thought it was ok in the output window before?

2024-05-14 06:57 UTC, rdstern commented
@N-thony this is all still a big improvement, so should I approve, so we can merge so far, and then discuss further?

2024-05-14 07:06 UTC, rdstern approved these changes
@Patowhiz I am really happy with the changes so far.  There is still a small question for a follow-up issue, but I would like to see this merged as soon as you are happy with the change.  Thanks

2024-05-14 10:26 UTC, Patowhiz requested changes

2024-05-14 10:26 UTC, Patowhiz commented on instat/dlgCalculator.vb
> +            ucrBase.clsRsyntax.iCallType = 1
I recommend removing the dependency on `iCallType`. Currently, within the `clsRLink.RunScript` subroutine, only the calculator dialog relies on `iCallType` to determine script execution. Initially, all dialogs were required to set `iCallType`, but we later shifted towards a model where scripts are executed in the same manner as they would be through the script window. This change is detailed in issue #7778.

If you can be able to use an approach that removes the dependency on `iCallType` we can then remove the code block in line 980 of  `clsRLink.RunScript` subroutine. This will improve the robustness and coherence of our base code. 

If doing the above needs more time, I'm happy to merge this as it is and later look into it.

2024-05-14 16:06 UTC, Patowhiz commented on instat/dlgCalculator.vb
> +            ucrBase.clsRsyntax.iCallType = 1
@N-thony I'm not sure what you mean by " I am afraid this can be the same with other dialogues?"
Did you have a look at my suggestions above? If you can address them then I'll merge this. In particular evaluating the time that it could take to remove the `iCallType` dependency for reasons outline in the issue I mentioned.

2024-05-14 16:21 UTC, Patowhiz commented on instat/dlgCalculator.vb
> +            ucrBase.clsRsyntax.iCallType = 1
No it was not correct, I agree with the changes made on line 312 of `clsRSyntax` in this PR.

2024-05-24 10:19 UTC, Patowhiz commented on instat/dlgCalculator.vb
> +            ucrBase.clsRsyntax.iCallType = 1
@N-thony I've seen that you have reverted the `iCallType` change.

Have you evaluated removing the dependency on `iCallType`? I've been wishing that for a long time, but if you feel that it will take a lot of your time, I'm happy to merge this as it is.

2024-05-29 19:42 UTC, rdstern reviewed
@N-thony I am really happy with the results when there is no data in R-Instat.

But once there is a data frame - survey for example,  In Version 7.6 I get this:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/3ed44bd5-13d5-4dbc-a7e3-b28e23efd44c)
  Not nice and not well formatted.

In the current pull request I get:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/2b27886d-6c4e-43c5-8ce1-944aa1c7097c)

So numbers well formatted, but do I have to also get the output below the data.  That'll be off-putting to R-Instat users - and me!

2024-06-01 09:02 UTC, rdstern commented
Thanks @N-thony I look forward to the results from your discussions.
There is a small - but would be very useful task hidden in #8931 which may need similar discussions?.  This is to display roman numerals in a data frame.  There is a calculator key (in the integer keyboard), and they display nicely as roman numerals in the Try and also in the R viewer.  But, in the data frame, they are transformed back into ordinary numbers, which destroys the point of showing roman numerals!

2024-06-15 09:13 UTC, rdstern approved these changes
Forgot this one.  @Patowhiz could you merge please!

2024-06-15 10:33 UTC, merged