Formatting Script
IDEMSInternational/R-Instat pull request #9153
Opened 2024-09-25 08:24 UTC by N-thony

fixes partly https://github.com/IDEMSInternational/R-Instat/issues/8847
@rdstern @derekagorhom have a look of the formatting of the script.
![image](https://github.com/user-attachments/assets/6c837a11-a5e4-4680-a659-19f79a27af69)
![image](https://github.com/user-attachments/assets/02fc4a3e-778b-48f9-9168-74993ab1d209)

2024-09-25 09:54 UTC, derekagorhom commented
@N-thony I tested this PR and it works, it also fixes the other issues with regards to my PR. 
@rdstern maybe able to give a more detailed review than me

2024-09-25 10:21 UTC, rdstern commented
@derekagorhom I must be missing something?  I loaded a script and pressed right-click and here is what I got:

![image](https://github.com/user-attachments/assets/903cbccc-0665-4edf-8662-705f711bdb74)

I don't see any difference, or formatting options?  What should I have done?  Should I have installed a package?

2024-09-25 10:26 UTC, derekagorhom commented
@rdstern The reformat option in on the Edit Menu now

2024-09-25 16:17 UTC, rdstern approved these changes
@N-thony that's great. 
I like the right-click, and I like it being called Reformat Code.
Do we still want the Format Code in the edit menu?  If so, should there be a line above and should it be Reformat Code for consistency with the right-click option?

I am approving while you consider this.  @Patowhiz could you check, react and merge?

2024-09-26 06:58 UTC, rdstern approved these changes
@Patowhiz this should be an easy check and merge?

2024-09-26 07:09 UTC, Patowhiz requested changes

2024-09-26 07:09 UTC, Patowhiz commented on instat/ucrScript.vb
> +        FormatRCode()
@N-thony if `FormatRCode()` is used once, then just put it's functionality inside the `mnuReformatCode` click event.
Same with `EscapeDoubleQuotes()` function. It's just one line and if used in one place only, just call the single line where it is used.
This will simplify the functionality added consequently making it easier to maintain.

2024-09-26 07:52 UTC, rdstern submitted a review, later dismissed

2024-09-26 08:18 UTC, Patowhiz commented on instat/ucrScript.vb
> +            If clsScriptActive.SelectionStart <> clsScriptActive.SelectionEnd Then
@N-thony I don't quite understand the need for this check. Line 1023 `Dim scriptText As String = clsScriptActive.SelectedText.Replace("""", "\""")` alreadu assumes there is selected text. That's why it is formatting the it. Why do you need to check for selection again? I though if there is no selection, formatting shouldn't happen.
If there is a case when you are allowed to format nothing, shouldn't the test for selection be done before line 1023 is executed?

2024-09-26 08:40 UTC, Patowhiz commented on instat/ucrScript.vb
> +            Dim formattedText As String = String.Join(Environment.NewLine, formattedCode)
What will happen when `formattedCode` is nothing? I think you can just place lines 1051 and 1054 inside the if block that checks for `expTemp`. For instance,

```
If expTemp IsNot Nothing AndAlso expTemp.Type <> Internals.SymbolicExpressionType.Null Then
                 Dim formattedCode As String() = expTemp.AsCharacter().ToArray
 ' Join the formattedCode array into a single string
            Dim formattedText As String = String.Join(Environment.NewLine, formattedCode)

' Replace the selected text with the formatted text
            clsScriptActive.ReplaceSelection(formattedText)
 End If
```

Then I think you won't need the try catch. You could have a message box in the else block that notifies users when formatting could not be done.

2024-09-26 08:59 UTC, Patowhiz commented on instat/ucrScript.vb
> +            Dim formattedText As String = String.Join(Environment.NewLine, formattedCode)
But that's what your try catch will do when `formattedCode` is nothing. In you code, you are changing `formattedCode` to a concatenated string even when it's nothing. That means an exception will be raised and the catch block will be executed, thus not 'providing your smoother experience'. That's why I asked about it. If the 'disruptive message' is not needed then you don't need the else block, that's why it's omitted in my code example above.

2024-09-26 09:22 UTC, Patowhiz submitted a review, later dismissed
@rdstern the code now looks good. Kindly retest then I can merge.

2024-10-11 10:21 UTC, Patowhiz approved these changes
@rdstern over to you to review.

2024-10-12 08:43 UTC, rdstern approved these changes
@N-thony and @Patowhiz that's very nice!

2024-10-12 09:03 UTC, merged