Version Number in the Frmmain code file
IDEMSInternational/R-Instat pull request #9161
Opened 2024-09-30 09:48 UTC by derekagorhom

From comments on PR #9159
https://github.com/IDEMSInternational/R-Instat/pull/9159#discussion_r1780639924
I have added the version number function into the code file 
@N-thony , @Patowhiz can you check and confirm
Thanks

2024-09-30 16:56 UTC, Patowhiz requested changes
@derekagorhom looks good. I have just made 1 suggestion change on the name of the subroutine to be more descriptive.

2024-09-30 16:56 UTC, Patowhiz commented on instat/frmMain.vb
> +    Public Sub VersionNumber()
```suggestion
    Public Sub SetAppVersionNumber()
```

2024-09-30 16:58 UTC, Patowhiz submitted a review, later dismissed

2024-09-30 16:58 UTC, Patowhiz commented on instat/frmMain.vb
> +        VersionNumber()
```suggestion
        SetAppVersionNumber()
```

2024-09-30 16:58 UTC, Patowhiz approved these changes
@N-thony this now looks good. Kindly check and merge.

2024-09-30 17:16 UTC, rdstern approved these changes
@N-thony I don't have #9163 though I see it here.  I am approving this one blinfly

2024-10-13 22:14 UTC, rdstern commented
@Patowhiz and @N-thony is this still needed?  The version number seems to be there now.  Should this be merged or closed?

2024-10-14 11:53 UTC, Patowhiz commented
@rdstern this is meant to put the code for displaying the version number in the correct place. 
@derekagorhom the code looks good and ready for merging. I was wondering whether we should remove the one in the designer file? Then we can merge this.

2024-10-14 12:14 UTC, derekagorhom commented
> @rdstern this is meant to put the code for displaying the version number in the correct place. @derekagorhom the code looks good and ready for merging. I was wondering whether we should remove the one in the designer file? Then we can merge this.

@Patowhiz I have removed the code in the designer file.....can you confirm and approve again.
Thanks

2024-10-14 13:58 UTC, rdstern approved these changes
@Patowhiz sounds good, so I am approving.  I don't know if you would simply like to approve and merge, or get @N-thony to do a final check and merge?

2024-10-15 06:03 UTC, Patowhiz approved these changes

2024-10-15 06:04 UTC, merged