Fixes bug in adding variable in multiple receiver
IDEMSInternational/R-Instat pull request #9311
Opened 2024-12-16 11:15 UTC by N-thony

Fixes #9306 I hope!

@derekagorhom have a look of this PR, it attempts to fix b) from the issue by adding of variable in the multipe reveiver, I think the issue was in the code with `FindItemWithText` which might only check for the beginning of the text (prefix matching) instead of the full string, or it could be performing partial matches therefore we were not able to add another variable.
You can work on item a)

2024-12-16 15:31 UTC, derekagorhom commented
@N-thony, It works now

2024-12-16 16:08 UTC, rdstern reviewed
@N-thony I believe you may have found that one.  Note it became apparent in more dialogs, including the summarise one.  Really noire to make R-Instat run more smoothly.
@derekagorhom as Antoine says, I hope you can fix the other feature in this issue, maybe in the same branch?

2024-12-18 18:04 UTC, rdstern commented
@derekagorhom are you ok to complete this pull request, or do you need help, or will it take time - in which case we could merge this change and have a new pull request?

2024-12-19 07:13 UTC, derekagorhom commented
@rdstern this pull request can be merged, it will be done on another pull request

2024-12-19 07:57 UTC, rdstern submitted a review, later dismissed
@N-thony,  @derekagorhom has suggested this be merged now and the other part becomes a separate pull request.
@Patowhiz please can you "do the honours"

2024-12-19 13:17 UTC, Patowhiz requested changes

2024-12-19 13:17 UTC, Patowhiz commented on instat/ucrReceiverMultiple.vb
> +            If item Is Nothing OrElse Not item.Text.Equals(kvpTempItem.Value, StringComparison.Ordinal) Then
@N-thony based on the official documentation in this [link](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.finditemwithtext?view=windowsdesktop-9.0) , I think it's safer to use a custom loop that searches for a full string match in the list of selected variables instead of relying on what is returned by `FindItemWithText`.

2024-12-23 09:06 UTC, Patowhiz commented
@rdstern Could you please test this with wide datasets to check for any significant performance degradation? Specifically, try using dialogs that have multiple receivers, as well as the Pivot Table dialog.

The code looks good, but I’d like to evaluate whether optimisation is necessary for wide datasets.

2025-01-09 17:48 UTC, rdstern commented
@N-thony I was looking for @Patowhiz wide data set when I stumbled over a different problem.
Try with our usual survey and `Describe > One Variable Summarise`.  Then add all variables and press Ok.

I get an error as follows:

![image](https://github.com/user-attachments/assets/fa27f4c5-6a40-472a-8c52-f75985671e77)

I give the code above and the error is correct, there is no object.

If you press Run again it is fine and the code is different - and back to what it should be.

2025-01-09 18:51 UTC, Patowhiz commented
@rdstern is that bug found in this PR only or it is also in the master branch. I'm also still waiting on you feedback on wide data sets.
Thanks.

2025-01-10 10:23 UTC, rdstern commented
@N-thony there isn't an issue on this.  I just stumbled over it, when testing this pull request for wide data sets.  So it was just reported here.  I'm now releived that the bug appeas=rs to be resolved, though I'd be even happier to discover why it happened as well.  Now I'm back to testing this one with wide data.

2025-01-11 13:22 UTC, rdstern approved these changes
@Patowhiz I tried with the first dataset from the extRemes package - with 12,000 variables.
It took 123 seconds to load into R-Instat, but then (in summarise) was reasonably instantaneous in transferring variables into the multiple receiver.
It did expose a small bug with wide data, but not to do with this code change.  So I'm approving.  Good to have fixed the bug.
@N-thony or @Patowhiz to merge.  Thanks to both.

2025-01-11 16:16 UTC, Patowhiz approved these changes

2025-01-11 16:16 UTC, merged