Implement Functionality to Restart R Within R-Instat
IDEMSInternational/R-Instat pull request #9319
Opened 2024-12-19 11:54 UTC by N-thony

Fixes partially #9308
@rdstern @jkmusyoka, this is a draft implementation of the functionality for restarting R within R-Instat. Please review and share your feedback.

2024-12-19 16:46 UTC, rdstern submitted a review, later dismissed
@N-thony this seems to work fine.  I'm approving and expecting @Patowhiz to also check.
I tried to look at why you might want to do this and it seems that it largely to do with the way R uses memory.
This nicely completes the main tasks in the Tools menu.  Should we now just get rid of the Run R Code and Save Current Options items?  That could be a separate pull request.

2025-01-23 07:34 UTC, rdstern commented
@ChrisMarsh82 could you please also look at this one?  It mirrors a facility in RStudio and we have asumed it in the Tools menu from the start.  And maybe merge once you are ok?

2025-02-04 10:12 UTC, ChrisMarsh82 commented
@ChrisMarsh82 line 2957 in main

2025-02-04 12:37 UTC, rdstern commented
@N-thony @ChrisMarsh82 has added a very brief message.  Is this locating the source of the conflicting files?  So back to you.

2025-02-05 09:47 UTC, ChrisMarsh82 requested changes
I can't see a way to get the memory to drop to origianl, although the changes do drop the memory back to close to where it was. Over a long period it seems to keep the memory consistent. I would suggest adding the forceGarbageCollection.

I looked at the threads and there is a possible memory leak in evaluate however this seems to reset when the procedure runs again so I don't think it is worth making changes here.

Is there something I am missing in your tests can you get the memory to keep going up?

2025-02-05 09:47 UTC, ChrisMarsh82 commented on instat/clsRLink.vb
> +
clsEngine.ForceGarbageCollection()
This doesn't seem to make too much difference to memory but is probably good to do.

2025-02-10 12:43 UTC, rdstern approved these changes
@ChrisMarsh82 and @N-thony I like the discussion above.  When I first ran it crashed out, saying pryr wasn't installed?
I assume it will be automatically in the new version?  After installing it ran nicely.  
I am happy to approve.  This (I think) now concludes the improvements we plan to make in the Tools menu?  So the remaining item here - or in a new issue - is to delete the 2 disabled items in that menu.  Namely Run R code, and save current options.

2025-02-25 17:49 UTC, rdstern commented
@ChrisMarsh82 I am hoping that we can merge some open pull requests tomorrow (Wenesday), ahead of merging @lilyclements implementation of the R-Packages.  Is this one you can approve, or should it wait?

2025-04-25 08:36 UTC, rdstern commented
@N-thony this would be good to merge, before you go, but it has conflicts.  Could you resolve them please?

2025-04-25 15:28 UTC, rdstern submitted a review, later dismissed
@lilyclements I am gambli ng here, but just a little.  And I don't see this does harm and it lets us "complete" the tools directory next week.  Could you also approve and merge?

2025-04-25 16:32 UTC, lilyclements commented
@N-thony can you fix this conflict so I can approve and merge?

2025-04-28 14:09 UTC, rdstern commented
@N-thony I am closing this pull request as it cannot be completed before your departure.

2025-04-28 17:31 UTC, closed without merging